framework:
    assets:
        packages:
            # shop:
            #     json_manifest_path: '%kernel.project_dir%/public/build/shop/manifest.json'
            # admin:
            #     json_manifest_path: '%kernel.project_dir%/public/build/admin/manifest.json'
            chullanka:
                json_manifest_path: '%kernel.project_dir%/public/build/chullanka/manifest.json'
