sylius_resource:
    resources:
        app.store:
            driver: doctrine/orm # You can use also different driver here
            classes:
                model: App\Entity\Chullanka\Store
                form: App\Form\Type\StoreType
                repository: App\Repository\Chullanka\StoreRepository
            translation:
                classes:
                    model: App\Entity\Chullanka\StoreTranslation
                    form: App\Form\Type\StoreTranslationType
        app.brand:
            driver: doctrine/orm
            classes:
                model: App\Entity\Chullanka\Brand
                form: App\Form\Type\BrandType
                repository: App\Repository\Chullanka\BrandRepository
            translation:
                classes:
                    model: App\Entity\Chullanka\BrandTranslation
                    form: App\Form\Type\BrandTranslationType
        app.faq:
            driver: doctrine/orm
            classes:
                model: App\Entity\Chullanka\Faq
                form: App\Form\Type\FaqType
                repository: App\Repository\Chullanka\FaqRepository
            translation:
                classes:
                    model: App\Entity\Chullanka\FaqTranslation
                    form: App\Form\Type\FaqTranslationType
        app.chulli:
            driver: doctrine/orm
            classes:
                model: App\Entity\Chullanka\Chulli
                form: App\Form\Type\ChulliType
                repository: App\Repository\Chullanka\ChulliRepository
        app.chulltest:
            driver: doctrine/orm
            classes:
                model: App\Entity\Chullanka\Chulltest
                form: App\Form\Type\ChulltestType
            translation:
                classes:
                    model: App\Entity\Chullanka\ChulltestTranslation
                    form: App\Form\Type\ChulltestTranslationType
        app.complementary_product:
            driver: doctrine/orm
            classes:
                model: App\Entity\Chullanka\ComplementaryProduct
                form: App\Form\Type\ComplementaryProductType
            translation:
                classes:
                    model: App\Entity\Chullanka\ComplementaryProductTranslation
                    form: App\Form\Type\ComplementaryProductTranslationType
        app.recall:
            driver: doctrine/orm
            classes:
                model: App\Entity\Chullanka\Recall
                form: App\Form\Type\RecallType
                repository: App\Repository\Chullanka\RecallRepository
        app.rma:
            driver: doctrine/orm
            classes:
                model: App\Entity\Chullanka\Rma
                form: App\Form\Type\RmaType
                repository: App\Repository\Chullanka\RmaRepository